apiVersion: apps/v1
kind: Deployment
metadata:
  name: library-frontend
  namespace: library-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: library-frontend
  template:
    metadata:
      labels:
        app: library-frontend
    spec:
      containers:
        - name: library-frontend
          image: library-frontend:latest   # Your frontend image
          imagePullPolicy: Never           # Since it's local
          ports:
            - containerPort: 8001
          env:
            # Environment variables for frontend
            - name: APP_ENV
              value: "dev"
            - name: APP_DEBUG
              value: "1"
            - name: API_BASE_URL
              value: "http://symfony-api.library-api.svc.cluster.local:8000"
