apiVersion: v1
kind: Service
metadata:
  name: library-frontend
  namespace: library-api
spec:
  type: NodePort
  selector:
    app: library-frontend
  ports:
    - port: 8001
      targetPort: 8001
      nodePort: 30002  # Expose on host for testing
