kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  # kubeadmConfigPatches:
  # - |
  #   kind: InitConfiguration
  #   nodeRegistration:
  #     kubeletExtraArgs:
  #       node-labels: "ingress-ready=true"
  extraPortMappings:
  - containerPort: 30002  # Port inside kind node
    hostPort: 30002       # Port exposed on Windows host
    protocol: TCP
